name: Technical Solutions
favicon: null
layout_spectrum: 0.19672
typography_spectrum: 0.10123
title: 'Come get it!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7c3b8'
    - '#ffffff'
    - '#c38571'
    - '#1d140f'
    - '#76716b'
  brandStrength: 0.824463508091867
  lightness: 0.5813040968496352
  saturation: 0.30336137232370675
  rhythmicContrast: 0.45909960055723786
purpose: []
