name: Technical Solutions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61349
title: 'Come get it!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#222222'
    - '#e1e1e1'
    - '#9e9e9e'
    - '#6f6f6f'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
