name: Technical Solutions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61349
title: 'Come get it!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c7c3ba'
    - '#36322f'
    - '#c2846d'
    - '#736e68'
  brandStrength: 0.824463508091867
  lightness: 0.5813040968496352
  saturation: 0.30336137232370675
  rhythmicContrast: 0.45909960055723786
purpose: []
